name: Tweet at 9:00am

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --release

      - name: Tweet
        run: target/release/kindle_daily_sale_twitter_bot